name: Autobuild

on: # Triggers the workflow on push events to only main
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs: # Define build and release
  release:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    steps: # The purpose of this part is to build the file and include it as a build artifact on GitHub
      - name: Get repo files
        uses: actions/checkout@v2
      - name: Setup build env
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          java-package: jdk
          check-latest: true
      - name: Compile
        run: ./gradlew build --no-daemon
      - name: Remove sources files and get specific jar
        run: |
          find -type f -path './build/libs/*' -name '*sources*' -delete
          echo "CFILELOC=$(find ./build/libs/* | grep .jar | head -1)" >> $GITHUB_ENV
      - name: Upload to Github Artifacts tab
        uses: actions/upload-artifact@v2
        with:
          name: FutureMC # This is the name that will appear in the Artifacts tab
          path: "${{ env.CFILELOC }}"
      - name: Release public builds # This will make in GitHub a tag and include a changelog based on the commits and can include the compiled jar
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: "${{ env.CFILELOC }}"
